export const CLOCK_DATA = [
  [
    { value: "I", type: "it" },
    { value: "T", type: "it" },
    { value: "T", type: "" },
    { value: "I", type: "is" },
    { value: "S", type: "is" },
    { value: "I", type: "" },
    { value: "T", type: "twenty" },
    { value: "W", type: "twenty" },
    { value: "E", type: "twenty" },
    { value: "N", type: "twenty" },
    { value: "T", type: "twenty" },
    { value: "Y", type: "twenty" },
  ],
  [
    { value: "Q", type: "quarter" },
    { value: "U", type: "quarter" },
    { value: "A", type: "quarter" },
    { value: "R", type: "quarter" },
    { value: "T", type: "quarter" },
    { value: "E", type: "quarter" },
    { value: "R", type: "quarter" },
    { value: "H", type: "half" },
    { value: "A", type: "half" },
    { value: "L", type: "half" },
    { value: "F", type: "half" },
    { value: "M", type: "" },
  ],
  [
    { value: "T", type: "m_ten" },
    { value: "E", type: "m_ten" },
    { value: "N", type: "m_ten" },
    { value: "F", type: "m_five" },
    { value: "I", type: "m_five" },
    { value: "V", type: "m_five" },
    { value: "E", type: "m_five" },
    { value: "E", type: "" },
    { value: "P", type: "past" },
    { value: "A", type: "past" },
    { value: "S", type: "past" },
    { value: "T", type: "past" },
  ],
  [
    { value: "T", type: "to" },
    { value: "O", type: "to" },
    { value: "A", type: "" },
    { value: "T", type: "twelve" },
    { value: "W", type: "twelve" },
    { value: "E", type: "twelve" },
    { value: "L", type: "twelve" },
    { value: "V", type: "twelve" },
    { value: "E", type: "twelve" },
    { value: "O", type: "one" },
    { value: "N", type: "one" },
    { value: "E", type: "one" },
  ],
  [
    { value: "T", type: "two" },
    { value: "W", type: "two" },
    { value: "O", type: "two" },
    { value: "T", type: "three" },
    { value: "H", type: "three" },
    { value: "R", type: "three" },
    { value: "E", type: "three" },
    { value: "E", type: "three" },
    { value: "F", type: "four" },
    { value: "O", type: "four" },
    { value: "U", type: "four" },
    { value: "R", type: "four" },
  ],
  [
    { value: "F", type: "five" },
    { value: "I", type: "five" },
    { value: "V", type: "five" },
    { value: "E", type: "five" },
    { value: "S", type: "six" },
    { value: "I", type: "six" },
    { value: "X", type: "six" },
    { value: "S", type: "seven" },
    { value: "E", type: "seven" },
    { value: "V", type: "seven" },
    { value: "E", type: "seven" },
    { value: "N", type: "seven" },
  ],
  [
    { value: "E", type: "eight" },
    { value: "I", type: "eight" },
    { value: "G", type: "eight" },
    { value: "H", type: "eight" },
    { value: "T", type: "eight" },
    { value: "N", type: "nine" },
    { value: "I", type: "nine" },
    { value: "N", type: "nine" },
    { value: "E", type: "nine" },
    { value: "T", type: "ten" },
    { value: "E", type: "ten" },
    { value: "N", type: "ten" },
  ],
  [
    { value: "N", type: "" },
    { value: "E", type: "eleven" },
    { value: "L", type: "eleven" },
    { value: "E", type: "eleven" },
    { value: "V", type: "eleven" },
    { value: "E", type: "eleven" },
    { value: "N", type: "eleven" },
    { value: "D", type: "" },
    { value: "D", type: "date" },
    { value: "A", type: "date" },
    { value: "T", type: "date" },
    { value: "E", type: "date" },
  ],
  [
    { value: "T", type: "" },
    { value: "I", type: "" },
    { value: "M", type: "" },
    { value: "E", type: "" },
    { value: "O", type: "oclock" },
    { value: "'", type: "oclock" },
    { value: "C", type: "oclock" },
    { value: "L", type: "oclock" },
    { value: "O", type: "oclock" },
    { value: "C", type: "oclock" },
    { value: "K", type: "oclock" },
    { value: "A", type: "" },
  ],
];
